apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluecompute
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: solsa1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/IBM/solsa-examples.git
    path: examples/bluecompute
    plugin:
      name: solsa
      env:
      - name: SOLSA_APP_MAIN
        value: bluecompute.js
  syncPolicy:
    automated:
      prune: true
