apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
spec:
  destination:
    namespace: solsa1
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/IBM/solsa-examples.git
    path: examples/bookinfo
    plugin:
      name: solsa
      env:
      - name: SOLSA_APP_MAIN
        value: instance.js
  syncPolicy:
    automated:
      prune: true
