apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcontainer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: solsa1
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/IBM/solsa-examples.git
    path: examples/k-container
    plugin:
      name: solsa
      env:
      - name: SOLSA_APP_MAIN
        value: kcontainer.js
  syncPolicy:
    automated:
      prune: true
