services:
  auth:
    replicaCount: 1
    image:
      repository: ibmcase/auth-mp
      tag: v3.0.0
    ports:
      http: 9080
      https: 9443
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  
  catalog:
    replicaCount: 1
    image:
      repository: ibmcase/catalog-mp
      tag: v3.0.0
    ports:
      http: 9080
      https: 9443
    volumes:
      mountPath: /opt/ibm/wlp/usr/shared
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  
  elasticsearch:
    replicaCount: 1
    image:
      repository: quay.io/pires/docker-elasticsearch-kubernetes
      tag: 1.7.1-4
    ports:
      http: 9200
      transport: 9300
    resources:
      limits:
        memory: 700Mi
      requests:
        memory: 350Mi
  
  cloudant:
    replicaCount: 1
    image:
      repository: ibmcom/cloudant-developer
      tag: 2.0.1
    ports:
      port: 80
    rootPassword: pass

  customer:
    replicaCount: 1
    image:
      repository: ibmcase/customer-mp
      tag: v4.0.0
    ports:
      http: 9080
      https: 9443
    volumes:
      mountPath: /opt/ibm/wlp/usr/shared
    jwt:
      id: myMpJwt
    cloudantInitJob:
      database: customers
      image:
        repository: ibmcase/populate
        tag: latest
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  
  inventory:
    replicaCount: 1
    image:
      repository: ibmcase/inventory-mp
      tag: v2.0.0
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
    ports:
      http: 9080
      https: 9443

  keystore:
    image:
      repository: ibmcase/keygen-mp
      tag: v3.0.0
    resources:
      requests:
        cpu: 200m
        memory: 300Mi

  mysql:
    image:
      repository: "mysql"
      tag: "5.7.14"
    ports:
      sql: 3306
    db:
      mysqlRootPassword: password
      mysqlUser: dbuser
      mysqlPassword: password
      mysqlDatabase: inventorydb
    service:
      port: 3306
    persistence:
      size: 8Gi
      accessMode: ReadWriteOnce
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  
  orders:
    replicaCount: 1
    image:
      repository: ibmcase/orders-mp
      tag: v4.0.0
    ports:
      http: 9080
      https: 9443
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
    service:
      name: orders
      servicePort: 9080
      servicePortHttps: 9443
      rabbitmq: rabbitmq
      ordersdb: mariadb
      inventory: inventory
      auth: auth
    sql:
      user: root
      password: password
      port: 3307
    jwt:
      id: myMpJwt
    rabbitmq:
      mainPort: 5672
      managePort: 15672
  
  mariadb:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 10.1.36-debian-9
    service:
      port: 3307
    rootUser:
      password: password
    db:
      user: dbuser
      password: password
      name: ordersdb
    replication:
      enabled: false
    master:
      persistence:
        enabled: false
        existingClaim:
        mountPath: ""
        annotations: {}
        storageClass:
        accessMode: ReadWriteOnce
        size: 8Gi
    slave:
      replicas: 1
      persistence:
        enabled: false
        annotations: {}
        storageClass:
        accessMode: ReadWriteOnce
        size: 8Gi
  
  web:
    replicaCount: 1
    image:
      repository: ibmcase/bc-web-mp
      tag: v2.0.0
    ports:
      http: 8000
    service:
      name: bluecompute-web
      externalPort: 80
      internalPort: 8000
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  zipkin:
    ports:
      zipkin: 9411
